### ISSUE TITLE
Consul registry 

### ISSUE THREAD

**Issue by linux-china** [linux-china/dubbo3#1]
集成Consul作为dubbo注册中心

**Comment by sundy20** [comment]
consul注册时没有添加healthcheck地址

**Comment by linux-china** [comment]
由于dubbo走的协议是特定的，而不是http的，目前有点麻烦。 @sundy20  你有什么好主意吗？

**Comment by sundy20** [comment]
consul java api里支持http tcp的heathcheck，可以使用telnet port方式的json报文check

**Comment by linux-china** [comment]
@sundy20  我打算添加一个环境变量，DUBBO_HTTP_CHECK_URL，这样我在spring boot和dubbo集成的时候就可以使用health进行测试，这样也可以做到服务优雅下线。

**Comment by sundy20** [comment]
嗯嗯，赞，目前我这边也是这么做的

**Comment by linux-china** [comment]
添加环境变量DUBBO_HTTP_CHECK_URL或者System.setProperty("DUBBO_HTTP_CHECK_URL","http://xxx") 这样来设置consul check
